include:
  - proxy.yaml

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.python
#    image: hw:1.0.2
    secrets:
      - env
    environment:
      - DB_HOST=db
    networks:
      backend:
        ipv4_address: 172.20.0.5
    restart: always

  db:
    image: mysql:8
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    networks:
      backend:
        ipv4_address: 172.20.0.10
    restart: on-failure

secrets:
  env:
    file: ./.env

networks:
  backend:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/24