include:
  - proxy.yaml
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.python
    environment:
      - DB_HOST=db
      - DB_NAME=${MYSQL_DATABASE}
      - DB_USER=${MYSQL_USER}
      - DB_PASSWORD=${MYSQL_PASSWORD}
    networks:
      backend:
        ipv4_address: 172.20.0.5
    restart: always
  db:
    image: mysql:8
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    volumes:
      - /opt/db:/var/lib/mysql
    networks:
      backend:
        ipv4_address: 172.20.0.10
    restart: on-failure
  cron:
    image: schnitzler/mysqldump
    restart: always
    volumes:
      - ./bin/root:/var/spool/cron/crontabs/root
      - ./bin/backup:/usr/local/bin/backup
    volumes_from:
      - backup
    command: ["-l", "8", "-d", "8"]
    environment:
      MYSQL_HOST: db
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    networks:
      backend:
        ipv4_address: 172.20.0.7
  backup:
    image: busybox
    volumes:
      - ./opt/backup:/backup
volumes:
  db_data:
networks:
  backend:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/24